# General Jekyll Config
kramdown:
  input: GFM

  coderay_line_numbers:


url: http://codeprivy.com
permalink: pretty
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
